language: go

go:
  - 1.6
  - 1.7
  - tip

before_script:
  - go install ./...
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - GO15VENDOREXPERIMENT=1 gometalinter --deadline 60s ./...
