language: go

go:
  - 1.5
  - 1.6
  - tip

before_script:
  - go install ./...
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  # disabled checks fail on tip
  - gometalinter --deadline 60s -D structcheck -D aligncheck ./...
