FROM alpine:3.6

RUN apk --update add go libc-dev

COPY . /go/src/github.com/bobrik/zoidbergtcp

RUN GOPATH=/go go install -v github.com/bobrik/zoidbergtcp/cmd/...

ENTRYPOINT ["/go/bin/zoidberg-tcp"]
